### ISSUE TITLE
Bug: Unexpected token error when encountering JSX

### ISSUE THREAD

**Issue by grantstrotter** [eslint/code-explorer#73]
### What did you do?

1. Open https://explorer.eslint.org/#eslint-explorer with default settings (which include JSX toggled on)
2. Put in an example including JSX, such as `const MyComponent = () => <>foo</>;`

### What did you expect to happen?

To see successfully rendered AST and Code Path tabs.

### What actually happened?

The AST and Code Path tabs say, "Error: Unexpected token < (1:27)"

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Confirmed, I can reproduce this. Please feel free to submit a PR. Thanks!

**Comment by grantstrotter** [comment]
Thanks. I unchecked "I am willing to submit a pull request for this issue" as I probably won't be able to prioritize troubleshooting and fixing this any time soon.

**Comment by nzakas** [comment]
Okay, I'll take a look.
